# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Organization.create(:name => 'Cockrell School of Engineering')
Organization.create(:name => 'College of Education')
Organization.create(:name => 'College of Fine Arts')
Organization.create(:name => 'College of Liberal Arts')
Organization.create(:name => 'College of Natural Sciences')
Organization.create(:name => 'College of Pharmacy')
Organization.create(:name => 'Dell Medical School')
Organization.create(:name => 'Graduate School')
Organization.create(:name => 'Jackson School of Geosciences')
Organization.create(:name => 'Lyndon B. Johnson School of Public Affairs')
Organization.create(:name => 'McCombs School of Business')
Organization.create(:name => 'Moody College of Communication')
Organization.create(:name => 'School of Architecture')
Organization.create(:name => 'School of Information')
Organization.create(:name => 'School of Law')
Organization.create(:name => 'School of Nursing')
Organization.create(:name => 'School of Social Work')
Organization.create(:name => 'School of Undergraduate Studies')

parent = TopicInterest.create(:name => 'Arts & Humanities')
TopicInterest.create(:name => 'Photography', :parent => parent)
TopicInterest.create(:name => 'History', :parent => parent)
TopicInterest.create(:name => 'Literature', :parent => parent)

parent = TopicInterest.create(:name => 'News & Media')
TopicInterest.create(:name => 'Newspapers', :parent => parent)
TopicInterest.create(:name => 'Radio', :parent => parent)
TopicInterest.create(:name => 'Weather', :parent => parent)
TopicInterest.create(:name => 'Blogs', :parent => parent)

parent = TopicInterest.create(:name => 'Business & Economy')
TopicInterest.create(:name => 'B2B', :parent => parent)
TopicInterest.create(:name => 'Finance', :parent => parent)
TopicInterest.create(:name => 'Shopping', :parent => parent)
TopicInterest.create(:name => 'Jobs', :parent => parent)

parent = TopicInterest.create(:name => 'Recreation & Sports')
TopicInterest.create(:name => 'Sports', :parent => parent)
TopicInterest.create(:name => 'Travel', :parent => parent)
TopicInterest.create(:name => 'Autos', :parent => parent)
TopicInterest.create(:name => 'Outdoors', :parent => parent)

parent = TopicInterest.create(:name => 'Computer & Internet')
TopicInterest.create(:name => 'Hardware', :parent => parent)
TopicInterest.create(:name => 'Software', :parent => parent)
TopicInterest.create(:name => 'Web', :parent => parent)
TopicInterest.create(:name => 'Games', :parent => parent)

parent = TopicInterest.create(:name => 'Reference')
TopicInterest.create(:name => 'Phone Numbers', :parent => parent)
TopicInterest.create(:name => 'Dictionaries', :parent => parent)
TopicInterest.create(:name => 'Quotes', :parent => parent)

parent = TopicInterest.create(:name => 'Education')
TopicInterest.create(:name => 'Colleges', :parent => parent)
TopicInterest.create(:name => 'K-12', :parent => parent)
TopicInterest.create(:name => 'Distance Learning', :parent => parent)

parent = TopicInterest.create(:name => 'Regional')
TopicInterest.create(:name => 'Countries', :parent => parent)
TopicInterest.create(:name => 'Regions', :parent => parent)
TopicInterest.create(:name => 'U.S. States', :parent => parent)

parent = TopicInterest.create(:name => 'Entertainment')
TopicInterest.create(:name => 'Movies', :parent => parent)
TopicInterest.create(:name => 'TV Shows', :parent => parent)
TopicInterest.create(:name => 'Music', :parent => parent)
TopicInterest.create(:name => 'Humor', :parent => parent)

parent = TopicInterest.create(:name => 'Science')
TopicInterest.create(:name => 'Animals', :parent => parent)
TopicInterest.create(:name => 'Astronomy', :parent => parent)
TopicInterest.create(:name => 'Earth Science', :parent => parent)

parent = TopicInterest.create(:name => 'Government')
TopicInterest.create(:name => 'Elections', :parent => parent)
TopicInterest.create(:name => 'Military', :parent => parent)
TopicInterest.create(:name => 'Law', :parent => parent)
TopicInterest.create(:name => 'Taxes', :parent => parent)

parent = TopicInterest.create(:name => 'Social Science')
TopicInterest.create(:name => 'Languages', :parent => parent)
TopicInterest.create(:name => 'Archaeology', :parent => parent)
TopicInterest.create(:name => 'Psychology', :parent => parent)

parent = TopicInterest.create(:name => 'Health')
TopicInterest.create(:name => 'Disease', :parent => parent)
TopicInterest.create(:name => 'Drugs', :parent => parent)
TopicInterest.create(:name => 'Fitness', :parent => parent)
TopicInterest.create(:name => 'Nutrition', :parent => parent)

parent = TopicInterest.create(:name => 'Society & Culture')
TopicInterest.create(:name => 'Sexuality', :parent => parent)
TopicInterest.create(:name => 'Religion', :parent => parent)
TopicInterest.create(:name => 'Food & Drink', :parent => parent)

LocationInterest.create(:name => 'Alabama')
LocationInterest.create(:name => 'Hawaii')
LocationInterest.create(:name => 'Massachusetts')
LocationInterest.create(:name => 'New Mexico')
LocationInterest.create(:name => 'South Dakota')
LocationInterest.create(:name => 'Alaska')
LocationInterest.create(:name => 'Idaho')
LocationInterest.create(:name => 'Michigan')
LocationInterest.create(:name => 'New York')
LocationInterest.create(:name => 'Tennessee')
LocationInterest.create(:name => 'Arizona')
LocationInterest.create(:name => 'Illinois')
LocationInterest.create(:name => 'Minnesota')
LocationInterest.create(:name => 'North Carolina')
LocationInterest.create(:name => 'Texas')
LocationInterest.create(:name => 'Arkansas')
LocationInterest.create(:name => 'Indiana')
LocationInterest.create(:name => 'Mississippi')
LocationInterest.create(:name => 'North Dakota')
LocationInterest.create(:name => 'Utah')
LocationInterest.create(:name => 'California')
LocationInterest.create(:name => 'Iowa')
LocationInterest.create(:name => 'Missouri')
LocationInterest.create(:name => 'Ohio')
LocationInterest.create(:name => 'Vermont')
LocationInterest.create(:name => 'Colorado')
LocationInterest.create(:name => 'Kansas')
LocationInterest.create(:name => 'Montana')
LocationInterest.create(:name => 'Oklahoma')
LocationInterest.create(:name => 'Virginia')
LocationInterest.create(:name => 'Connecticut')
LocationInterest.create(:name => 'Kentucky')
LocationInterest.create(:name => 'Nebraska')
LocationInterest.create(:name => 'Oregon')
LocationInterest.create(:name => 'Washington')
LocationInterest.create(:name => 'Delaware')
LocationInterest.create(:name => 'Louisiana')
LocationInterest.create(:name => 'Nevada')
LocationInterest.create(:name => 'Pennsylvania')
LocationInterest.create(:name => 'West Virginia')
LocationInterest.create(:name => 'Florida')
LocationInterest.create(:name => 'Maine')
LocationInterest.create(:name => 'New Hampshire')
LocationInterest.create(:name => 'Rhode Island')
LocationInterest.create(:name => 'Wisconsin')
LocationInterest.create(:name => 'Georgia')
LocationInterest.create(:name => 'Maryland')
LocationInterest.create(:name => 'New Jersey')
LocationInterest.create(:name => 'South Carolina')
LocationInterest.create(:name => 'Wyoming')

# This is a basic user
user1 = User.create(:name => 'Test User', :email => 'example@example.com', :password => 'password')

profile1 = InterestProfile.create(:user => user1, :name => 'Profile 1')
ProfileOrganization.create(:interest_profile => profile1, :organization => Organization.first)
ProfileLocation.create(:interest_profile => profile1, :location_interest => LocationInterest.first)
ProfileTopic.create(:interest_profile=> profile1, :topic_interest => TopicInterest.first)

profile2 = InterestProfile.create(:user => user1, :name => 'Profile 2')
ProfileOrganization.create(:interest_profile => profile2, :organization => Organization.last)
ProfileLocation.create(:interest_profile => profile2, :location_interest => LocationInterest.last)
ProfileTopic.create(:interest_profile=> profile2, :topic_interest => TopicInterest.last)

# This is a user slightly similar to user1
user2 = User.create(:name => 'Different User', :email => 'different@example.com', :password => 'password')

profile1 = InterestProfile.create(:user => user2, :name => 'Other Profile 1')
ProfileOrganization.create(:interest_profile => profile1, :organization => Organization.last)
ProfileLocation.create(:interest_profile => profile1, :location_interest => LocationInterest.first)
ProfileTopic.create(:interest_profile=> profile1, :topic_interest => TopicInterest.last)

profile2 = InterestProfile.create(:user => user2, :name => 'Other Profile 2')
ProfileOrganization.create(:interest_profile => profile2, :organization => Organization.first)
ProfileLocation.create(:interest_profile => profile2, :location_interest => LocationInterest.last)
ProfileTopic.create(:interest_profile=> profile2, :topic_interest => TopicInterest.first)

# This user is completely different from user1
user3 = User.create(:name => 'Very Different User', :email => 'very.different@example.com', :password => 'password')

profile1 = InterestProfile.create(:user => user3, :name => 'Different Profile 1')
ProfileOrganization.create(:interest_profile => profile1, :organization => Organization.second)
ProfileLocation.create(:interest_profile => profile1, :location_interest => LocationInterest.second)
ProfileTopic.create(:interest_profile=> profile1, :topic_interest => TopicInterest.second)

profile2 = InterestProfile.create(:user => user3, :name => 'Different Profile 2')
ProfileOrganization.create(:interest_profile => profile2, :organization => Organization.third)
ProfileLocation.create(:interest_profile => profile2, :location_interest => LocationInterest.third)
ProfileTopic.create(:interest_profile=> profile2, :topic_interest => TopicInterest.third)
